// Shared content for all three site variants.
const SITE_DATA = {
  name: 'Anshul Dhawan',
  tagline: 'Generalist & game developer',
  about: [
    "I'm co-founder of PlayWorlds, where I'm building the first AI-native creation platform for kids. I bring 15 years of experience scaling gaming, social, and AI products across some of the largest live-service and multiplayer platforms in the industry.",
    "Most recently, I founded Social Pixels, an AI-native gaming studio that achieved 20x efficiency improvements in cost and time-to-market for game production. Before that, I was VP of Product and Analytics at Supernatural VR, which was acquired by Meta in a deal reported at about $400M.",
    "I led product at VRChat, one of the defining social VR platforms, and served as Senior Director of Product and Business Intelligence at Glu Mobile / EA.",
    {
      text: "I spent the first seven-plus years of my career at Zynga, rising from software engineer to Head of Product, Growth, leading the development of ",
      link: { label: "Zynga's learning machine", href: '/projects/experimentation-service/' },
      after: ". I also founded Equally, an AI-powered AR learning platform ",
      secondLink: { label: 'Da Vinci Club AR', href: '/projects/da-vinci-club-ar/' },
      secondAfter: '.',
    },
  ],
  companyLogos: [
    { name: 'Meta', href: 'https://www.meta.com/', logo: 'https://www.google.com/s2/favicons?domain=meta.com&sz=128' },
    { name: 'Zynga', href: 'https://www.zynga.com/', logo: 'https://www.google.com/s2/favicons?domain=zynga.com&sz=128' },
    { name: 'EA', href: 'https://www.ea.com/', logo: 'https://cdn.simpleicons.org/ea/111111?viewbox=auto' },
    { name: 'VRChat', href: 'https://hello.vrchat.com/', logo: 'https://www.google.com/s2/favicons?domain=vrchat.com&sz=128' },
  ],
  projects: [
    {
      slug: 'poker-tournament',
      title: 'Claude vs ChatGPT vs Gemini vs Grok — Poker Tournament',
      role: 'Builder',
      tag: 'LLM evaluation',
      blurb: "A Texas Hold'em evaluation harness that pits frontier LLMs against each other across hands and tournaments.",
      content: [
        "A Texas Hold'em evaluation harness that pits frontier LLMs against each other across hands and tournaments.",
        "Designed to surface which models actually reason under uncertainty — bluffing, bet sizing, opponent modeling — versus which ones just play textbook ranges.",
        "A useful proxy for agentic decision-making beyond standard benchmarks.",
      ],
      year: '2026',
      media: { type: 'video', src: '/assets/videos/poker-tournament.mp4', poster: '/assets/posters/poker-tournament.jpg', aspect: '1330/1080' },
      links: [],
    },
    {
      slug: 'network-cities',
      title: 'Network Cities',
      role: 'Founder · Social Pixels',
      tag: 'AI-native game',
      blurb: "A city builder where every part of the development pipeline is generative — concept art, 3D assets, characters, game code, and server code, all produced by AI agents.",
      content: [
        "A city builder where every part of the development pipeline is generative. Concept art, 3D assets, characters, game code, and server code — all produced by AI agents.",
        "Includes an agent for automated game analytics that monitors live gameplay and flags balance issues.",
        "The thesis: a small team plus the right agent stack can ship a category of games that used to need 50+ people.",
      ],
      year: '2025 —',
      media: { type: 'video', src: '/assets/videos/network-cities.mp4', poster: '/assets/posters/network-cities.jpg', aspect: '16/9' },
      links: [],
    },
    {
      slug: 'da-vinci-club-ar',
      title: 'Da Vinci Club AR',
      role: 'Builder',
      tag: 'AR · EdTech',
      blurb: "A computer-vision-based AR app for kids that turned the world around them into a learning surface.",
      content: [
        "A computer-vision-based AR app for kids that turned the world around them into a learning surface.",
        "Point the phone at an object and the app would let kids go down a rabbit hole of related concepts — letting curiosity drive the curriculum instead of a fixed lesson plan.",
      ],
      year: '',
      media: { type: 'video', src: '/assets/videos/davinci-club-ar.mp4', poster: '/assets/posters/davinci-club-ar.jpg', aspect: '16/9' },
      links: [],
    },
    {
      slug: 'experimentation-service',
      title: 'Experimentation & Optimization Service',
      role: 'Product · Zynga',
      tag: 'Platform',
      blurb: "Server-side experimentation and optimization service for Zynga that let PMs and analysts ship experiments without engineering bottlenecks.",
      content: [
        "Zynga's edge was testing more ideas than anyone else, but after the mobile transition the old experimentation platform got slow — every test needed a client release.",
        "I led the build of a server-side experimentation and optimization service that let PMs and analysts configure, segment, and ship experiments without engineering bottlenecks.",
        "Earned a SPIRIT award (given for setting a new company standard).",
      ],
      year: '2014 — 2017',
      media: null,
      links: [
        { label: 'Patent', href: 'https://patents.google.com/patent/US9737815B2' },
      ],
    },
    {
      slug: 'words-with-degens',
      title: 'Words with Degens',
      role: 'Builder',
      tag: 'Game · crypto',
      blurb: "A scramble game you play with friends, built around crypto lingo. Launched on play.fun with on-chain rewards for winners.",
      content: [
        "A scramble game you play with friends, built around crypto lingo. Launched on play.fun with on-chain rewards for winners.",
        "The bet was that crypto-native vocabulary plus social play could create a wedge in word games. Small surface area, fast loop, easy to share.",
      ],
      year: '2025',
      media: { type: 'image', src: '/assets/images/words-with-degens.png', alt: 'Words with Degens game poster', aspect: '1/1' },
      links: [
        { label: 'play.fun', href: 'https://play.fun' },
      ],
    },
    {
      slug: 'global-learning-xprize',
      title: 'Global Learning XPrize',
      role: 'Builder',
      tag: 'EdTech · Semi-finalist',
      blurb: "Semi-finalist in the $15M Global Learning XPrize, a competition for teams building software to teach literacy and numeracy to kids without access to schools or teachers.",
      content: [
        "Semi-finalist in the $15M Global Learning XPrize — a competition for teams building software to teach literacy and numeracy to kids without access to schools or teachers.",
        "We built an intelligent game that adapted difficulty in real time to each child's learning speed.",
      ],
      year: '2017',
      media: { type: 'image', src: '/assets/images/global-learning-xprize.jpg', alt: 'Global Learning XPrize semi-finalist plaque', aspect: '1275/843' },
      links: [
        { label: 'XPrize', href: 'https://www.xprize.org/competitions/global-learning' },
      ],
    },
    {
      slug: 'player-recommendation',
      title: 'Player Recommendation System',
      role: 'Product · Zynga',
      tag: 'Matchmaking',
      blurb: "A skill-based matchmaking system that pairs players for more balanced and engaging sessions.",
      content: [
        "A skill-based matchmaking system that pairs players for more balanced and engaging sessions.",
        "Better matches mean longer sessions and stickier games. Patent issued.",
      ],
      year: '2013',
      media: null,
      links: [
        { label: 'Patent', href: 'https://patents.google.com/patent/US20140274362' },
      ],
    },
  ],
  writings: [
    {
      slug: 'what-is-spirituality',
      title: 'What is Spirituality?',
      date: '2025 · 04',
      blurb: 'On spirit, identity, meditation, gratitude, affirmations, and living consciously.',
      content: [
        'Spirituality is a way of living with a constant realization that we are "ALL" spirits. And "ALL" includes all of humanity, all of the animal kingdom, all the birds, all the fishes, and all of plant life.',
        'Naturally, we live with our inherited identities that we did not choose. We live with what our mind and ego think is us. And that is essentially what stops us from reaching this realization.',
        'So spirituality, in other words, is not allowing your mind to drive your life but allowing your heart to drive your life.',
        'It is commonly said to do what your heart says or listen to your heart; however, guess what? The heart does not say anything, no matter how closely we listen. At best, we will hear a heartbeat.',
        'What we attribute to the heart is nothing. It is what our spirit wants.',
        'But because we cannot see the spirit, we assign its role to the heart.',
        {
          type: 'heading',
          text: 'So, how does one become spiritual?',
        },
        'There are unlimited ways to become spiritual and have this realization. One of the modern, immediately effective, however unsuitable ways to have this realization is by consuming psychedelics.',
        'Psychedelics break the structures associated in our mind with our ego and identity, making us see the world as spirits.',
        'Unfortunately, that realization and outlook go away with time unless you consume psychedelics again.',
        'One of the oldest, slowly effective but sustainable ways to become spiritual is meditation.',
        'However, meditation without the knowledge that we are all made of three components - mind, body, and spirit - is likely not going to make anyone spiritual.',
        'Meditation without this knowledge will still calm your mind, which in itself is a great outcome; however, to truly become spiritual, one has to go really deep into the meditation practice and control one\'s mind.',
        {
          type: 'heading',
          text: 'How does one control one\'s mind?',
        },
        'This is where the mind-body connection comes in. There is only one activity we do unconsciously and consciously, and that is breathing. By breathing consciously, we can bring the mind into a conscious state from the usual autopilot state it is always in by default.',
        {
          type: 'subheading',
          text: 'Deep breathing',
        },
        'By breathing deeply, we can observe our minds from a third-person perspective. We can notice our thoughts and focus wandering endlessly from one worry to another, one task to another.',
        'With some little practice, we get better at maintaining our focus on our breath and letting go of our thoughts briefly.',
        'Once this state is achieved, the basic level of meditation, aka the basic level of awareness called mindfulness, can be achieved.',
        'Deep breathing means ...',
        {
          type: 'subheading',
          text: 'Gratitude',
        },
        'To reach the next state, one must go from basic deep breathing to the state of gratitude. In the state of gratitude, one starts to consciously start being thankful for everything major and minor happening in one\'s life.',
        'One can be thankful for an infinite number of things that are working well in one\'s life: good health, happy moments with friends, supporting family, sunny days, a sports team winning, new episodes of a favorite show dropping, the list goes on.',
        'This practice re-programs the mind to look for more things to be grateful for, thereby helping one go deep even further.',
        {
          type: 'subheading',
          text: 'Affirmations',
        },
        'To reach the next state, one must start associating themselves with the attributes, traits and state of mind they want to be in. In this state, one reprograms their mind by suffixing desired attributes, traits and state of mind to "I am".',
        'One can attribute an infinite number of things to themselves like I am calm, I am kind, I am protected, I am capable of anything, I am funny, I am ...',
        'These meditation practices provide a very strong foundation for living a conscious spiritual life. However, the real work starts with trying to live consciously.',
        {
          type: 'heading',
          text: 'Scientific Studies Validating the Claims',
        },
        {
          type: 'orderedList',
          items: [
            {
              title: 'Impact of Psychedelics on Spirituality',
              text: 'Research has shown that psychedelics like psilocybin can induce profound spiritual experiences. A study published in the Journal of Psychopharmacology found that psilocybin can lead to long-lasting increases in the personality domain of openness, which is associated with creativity and spirituality (Griffiths et al., 2006).',
            },
            {
              title: 'Meditation and Spirituality',
              text: 'Numerous studies support the claim that meditation can enhance spiritual experiences. For instance, a study in the Journal of Alternative and Complementary Medicine found that regular meditation practice is associated with increased spiritual well-being and reduced psychological distress (Shapiro et al., 2008).',
            },
            {
              title: 'Mindfulness and Mental Health',
              text: 'The discussion on mindfulness and its benefits is supported by scientific literature. Mindfulness-based cognitive therapy has been shown to reduce symptoms of depression and anxiety by promoting a state of awareness and acceptance (Kabat-Zinn, 2003).',
            },
            {
              title: 'Gratitude and Psychological Well-being',
              text: 'The practice of gratitude has been linked to improved mental health. A study in Personality and Individual Differences found that gratitude is strongly correlated with well-being and positive affect (Wood et al., 2010).',
            },
            {
              title: 'Affirmations and Self-Concept',
              text: 'Affirmations can positively impact self-esteem and self-concept. Research in Psychological Science has shown that self-affirmation exercises can buffer stress and improve problem-solving abilities (Creswell et al., 2005).',
            },
          ],
        },
        'These studies provide empirical support for the claims made in the text about the benefits of psychedelics, meditation, mindfulness, gratitude, and affirmations in fostering a spiritual life.',
        {
          type: 'heading',
          text: 'References',
        },
        {
          type: 'orderedList',
          items: [
            'Griffiths, R. R., Richards, W. A., McCann, U., & Jesse, R. (2006). Psilocybin can occasion mystical-type experiences having substantial and sustained personal meaning and spiritual significance. Journal of Psychopharmacology, 20(5), 620-632.',
            'Shapiro, S. L., Oman, D., Thoresen, C. E., Plante, T. G., & Flinders, T. (2008). Cultivating mindfulness: Effects on well-being. Journal of Alternative and Complementary Medicine, 14(3), 293-298.',
            'Kabat-Zinn, J. (2003). Mindfulness-based interventions in context: Past, present, and future. Clinical Psychology: Science and Practice, 10(2), 144-156.',
            'Wood, A. M., Froh, J. J., & Geraghty, A. W. (2010). Gratitude and well-being: A review and theoretical integration. Clinical Psychology Review, 30(7), 890-905.',
            'Creswell, J. D., Welch, W. T., Taylor, S. E., Sherman, D. K., Gruenewald, T. L., & Mann, T. (2005). Affirmation of personal values buffers neuroendocrine and psychological stress responses. Psychological Science, 16(11), 846-851.',
          ],
        },
        {
          type: 'heading',
          text: 'Additional Links',
        },
        {
          type: 'linkList',
          items: [
            { label: 'Wikipedia: Spirituality', href: 'https://en.wikipedia.org/wiki/Spirituality' },
            { label: 'Merriam-Webster: Spirituality', href: 'https://www.merriam-webster.com/dictionary/spirituality' },
            { label: 'Royal College of Psychiatrists: What is spirituality?', href: 'https://www.rcpsych.ac.uk/docs/default-source/members/sigs/spirituality-spsig/what-is-spirituality-maya-spencer-x.pdf?sfvrsn=f28df052_2' },
            { label: 'Psychology Today: Spirituality', href: 'https://www.psychologytoday.com/us/basics/spirituality' },
            { label: 'Taking Charge: What is spirituality?', href: 'https://www.takingcharge.csh.umn.edu/what-spirituality' },
          ],
        },
      ],
      images: [
        {
          kind: 'hero',
          src: '/assets/images/what-is-spirituality-mask.png',
          alt: 'Colorful artwork of a figure lifting a mask to reveal a bright landscape with mountains, flowers, and a butterfly',
          aspect: '642/636',
          credit: {
            label: 'Image by RozziRoomian',
            href: 'https://www.rozziroomian.com/store/p/the-mask-canvas-prints',
          },
        },
        {
          after: 27,
          src: '/assets/images/what-is-spirituality-meditation.png',
          alt: 'A meditating figure in a luminous natural landscape with breath-like light connecting plants, birds, water, and mountains',
          aspect: '3/2',
        },
      ],
    },
    {
      slug: 'emotion-and-rationality-of-decision-making',
      title: 'Emotion and Rationality in Decision-Making',
      date: '2025 · 04',
      blurb: 'On using emotion as signal and rationality as refinement.',
      content: [
        'I generally believe that better decisions come from balancing emotion and rationality. The tricky part is that the balance is rarely obvious in the moment. I often notice myself having an emotional response first, then building a rational story around it afterward. The logic can feel clean, but underneath it there is still an initial pull that shaped the conclusion before I had fully examined it.',
        'At other times, I overcorrect. I notice the emotion, distrust it, and try to make the decision from a purely rational place. That can feel disciplined, but it can also become detached. Emotion usually carries information: anxiety may point toward risk, excitement may point toward desire, frustration may point toward a boundary being crossed. Ignoring that information completely can flatten the decision.',
        'The danger is letting emotion drive unchecked. Emotional reactions are fast and useful, but they can also be impulsive, biased, or rooted in short-term discomfort. They can make one option feel obviously right simply because it relieves pressure now. In those moments, rationality is useful because it slows the reaction down. It asks what evidence exists, what tradeoffs matter, and whether the feeling is responding to a real signal or just the fear of uncertainty.',
        'Rational thinking gives structure. It helps compare consequences, surface assumptions, and separate the immediate feeling from the longer-term outcome. But rationality alone has its own failure mode. It can optimize for what is measurable while missing what is meaningful. It can create a cold answer that looks correct on paper but does not account for values, relationships, or the emotional cost of carrying the decision forward.',
        'The version I am trying to practice is not emotion versus rationality, but emotion followed by inquiry. First, notice the feeling without immediately obeying it or dismissing it. Then ask what it might be protecting, revealing, or exaggerating. After that, use rational analysis to refine the response into something more deliberate.',
        'In personal decisions, emotions often deserve more weight because they reveal values and needs that may not fit neatly into a spreadsheet. In professional decisions, rationality may need to lead more often, but emotional intelligence still matters: understanding how people feel, how incentives shape behavior, and how trust is built or lost.',
        'A good decision is not always the one that feels best, and it is not always the one that looks most logical in isolation. It is the one where the emotional signal has been heard, the rational case has been tested, and neither side is secretly running the whole process alone.',
      ],
      images: [
        {
          kind: 'hero',
          src: '/assets/images/emotion-and-rationality-decision-making-hero.png',
          alt: 'Thoughtful figure behind a gold balance scale with an amber heart and phosphor-green wireframe brain',
          aspect: '3/2',
        },
        {
          after: 4,
          src: '/assets/images/emotion-and-rationality-decision-making-prism.png',
          alt: 'Dark CRT-style decision flow with a balance scale, heart, wireframe brain, inquiry prism, and check mark',
          aspect: '3/2',
        },
      ],
    },
    {
      slug: 'the-issue-of-neat-categorization',
      title: 'The issue of neat categorization',
      date: '2025 · 04',
      blurb: 'On why categories help us think, and what they quietly leave out.',
      content: [
        'I recently realized how much of a knack we have for categorizing things in order to understand them. Essentially, we make things simple so we can pattern match more easily.',
        "Categorization helps us simplify complex information, but it often comes with a trade-off: some level of nuance and complexity is lost in the process. When we force things into neat categories, we might overlook details that do not fit into the predefined boxes. This can lead to oversimplification, where we lose the richness of context and the subtle relationships between things that do not fit as easily.",
        "For example, in biology, we categorize species into families, genera, and other ranks, but this sometimes ignores evolutionary anomalies or hybrid species that do not fit perfectly into those categories. Similarly, in human behavior, labeling people as introverts or extroverts can ignore the fluidity and context-specific nature of those traits.",
        'The same problem shows up in medicine. A diagnosis can be useful because it gives doctors a shared language and a known treatment path, but real bodies often contain overlapping symptoms, comorbidities, edge cases, and histories that do not behave like clean textbook entries.',
        'Maps are another example. Borders, neighborhoods, and regions make territory legible, but lived culture rarely stops exactly where a line is drawn. A city can contain many cities inside it, and a language can fade into another through dialects, accents, and local usage instead of switching cleanly from one category to the next.',
        'Culture also resists neat sorting. Music, art, games, and films are grouped into genres so we can find and discuss them, but the most interesting work often lives between genres. Political labels work the same way: they can compress a worldview into a word, while hiding the contradictions, priorities, and context that actually shape a person.',
        'This becomes even sharper in algorithmic systems. Recommendation engines, moderation systems, resumes, ads, and user segments all depend on labels, but a label can mistake convenience for truth. Once the system starts acting on the label, the category can shape the reality it was only supposed to describe.',
        'At the same time, categorization is a natural cognitive tool for making sense of the world around us. It helps us process and recall information more efficiently, even if that efficiency means losing some complexity along the way.',
      ],
      images: [
        {
          kind: 'hero',
          src: '/assets/images/the-issue-of-neat-categorization-hero.png',
          alt: 'Abstract phosphor-green taxonomy grid with organic forms spilling outside the boxes',
          aspect: '3/2',
        },
        {
          after: 2,
          src: '/assets/images/the-issue-of-neat-categorization-spectrum.png',
          alt: 'Abstract phosphor-green spectrum of human silhouettes and organic branching lines between categories',
          aspect: '3/2',
        },
        {
          after: 6,
          src: '/assets/images/the-issue-of-neat-categorization-examples.png',
          alt: 'Abstract phosphor-green composition of medicine, maps, culture, politics, language, and algorithms escaping a taxonomy grid',
          aspect: '3/2',
        },
      ],
    },
    {
      slug: 'three-perspectives-on-reality',
      title: 'Three Perspectives on Reality',
      date: '2024',
      blurb: 'On moving between broad, close, and metaphysical views of reality.',
      content: [
        "I have noticed that when you analyze something deeply, it helps to move between two perspectives. One is the bird's-eye view, where you look from high above and understand the whole shape of the thing. The other is the worm's-eye view, where you get close enough to see the details, textures, and hidden mechanics.",
        'Another way to say this is: we can get so lost in the trees that we do not realize we are in the wrong forest.',
        'Then there is a third way: a way to look at things from outside the physical world, at the metaphysical level.',
        "At this level, you move beyond the immediate context, the material realm, and even the limits of perception. It is about understanding the underlying principles, or universal truths, that govern existence, consciousness, and reality itself. It is a broader and more abstract view, where questions of meaning, purpose, and the nature of the universe come into focus.",
        "For instance, while a bird's-eye view gives you a broad overview of a situation, and a worm's-eye view lets you examine the details up close, the metaphysical view steps back further to consider the greater forces at play. It is like stepping out of the forest entirely to understand not just where you are in it, but how the entire forest fits within the broader ecosystem.",
      ],
      images: [
        {
          kind: 'hero',
          src: '/assets/images/three-perspectives-on-reality-birds-eye.png',
          alt: "Abstract phosphor-green bird's-eye map of a forest canopy",
          aspect: '3/2',
        },
        {
          after: 0,
          src: '/assets/images/three-perspectives-on-reality-worms-eye.png',
          alt: "Abstract phosphor-green close-up of roots and layered earth",
          aspect: '3/2',
        },
        {
          after: 3,
          src: '/assets/images/three-perspectives-on-reality-metaphysical.png',
          alt: 'Abstract phosphor-green metaphysical geometry around a forest system',
          aspect: '3/2',
        },
      ],
    },
    {
      slug: 'generative-games',
      title: 'Generative Games on building systems that generate games',
      date: '2025 · 03',
      blurb: 'On building systems that generate games, and what that changes about the medium.',
      content: [
        'The future of the gaming industry is going to be Generative Games.',
        'Once upon a time, the industry used to think games were products you shipped once. Then came MMOs that showed games did not have to be "shipped and done," and games became services, economies, and habits. Zynga scaled that idea into the mainstream and proved that the real game was not just the content but the system that kept players coming back.',
        'GenAI blows that model open. I believe we are moving beyond games that are merely updated by developers. We are entering a world where characters, rules, stories and even parts of the world can be generated and adapted in real time. The game is no longer fixed. It becomes responsive and increasingly alive.',
        'That shift is bigger than better content pipelines or cheaper asset creation. It changes the nature of the medium itself. For decades, game development has been about hand-authoring experiences. With generative systems, the experience can evolve while the player is inside it. Worlds can react to play styles. Missions can emerge instead of being fully scripted. Social dynamics can shape the state of the world rather than just sit on top of it.',
        'This creates a new design frontier. The job is no longer only to build levels, characters, and mechanics. The job is to design systems that can generate interesting possibility spaces while staying coherent and fun.',
        'It also changes what "live ops" means. Live ops used to mean events, content drops, balance changes and monetization loops. In generative games, live ops can become continuous world steering. Developers set the direction, constraints, and incentives, while the game itself participates in creating fresh play. The operating model shifts from shipping updates to managing living systems.',
        'Of course, this does not mean every game should become fully generative. A lot of great game design comes from intention, curation, and handcrafted constraints. But the ceiling has clearly moved. The most interesting games of the next decade will likely combine authored taste with generative adaptability. Not infinite randomness but living systems with taste.',
        'And just like social games changed what people optimized for, generative games will change what developers will optimize for. The winners may not be the teams that produce the most content. They may be the ones that build the best feedback loops between player behavior, AI systems and world evolution.',
        'We are still early, but the direction feels clear. Games are starting to move from static software to dynamic worlds.',
      ],
      images: [
        {
          kind: 'hero',
          src: '/assets/images/generative-games-living-world.png',
          alt: 'A luminous isometric game world being generated from authored systems and adaptive AI particles',
          aspect: '3/2',
        },
      ],
    },
    {
      slug: 'generalist-case',
      title: "A generalist's case for staying a generalist",
      date: '2025 · 11',
      blurb: 'Notes on optimizing for breadth in a world that keeps asking you to specialize.',
      content: [],
    },
  ],
  links: [
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/anshuldhawan/' },
    { label: 'X / Twitter', href: 'https://x.com/AnshulDhawan001' },
  ],
};

window.SITE_DATA = SITE_DATA;
